# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    display-name: 'First Name'
    description: 'Who to greet'
    required: true
    default: 'World'
  test:
    description: 'test'
    requied: true
    default: 'ABC'
outputs:
  time: # id of output
    description: 'The time we greeted you'
  test: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    - ${{ inputs.test }}
