on: [push]

jobs:
  gpSecurityJob:
    name: GP Security Check Job
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: GP Security Check Step
        id: gp-security-check
        uses: whitesource/GitHubPackagesSecurityAction@19.10.2
        with:
          gp-token: ${{ secrets.GP_ACCESS_TOKEN }}
          ws-api-key: ${{ secrets.WS_KEY }}
          ws-user-key: ${{ secrets.WS_KEY }}
          ws-product-key: ${{ secrets.WS_KEY }}
          ws-destination-url: https://saas.whitesourcesoftware.com/agent
          print-scan-report: true
          actions_step_debug: true

