on: [push]

jobs:
  hello_world_job:
    runs-on: self-hosted
    name: A job to say hello
    steps:
    - name: GP Security Scan
      # You may pin to the exact commit or the version.
      # uses: whitesource/GitHubPackagesSecurityAction@b5f36d0e95550dd5699e967862e882fcee19fa2c
      uses: whitesource/GitHubPackagesSecurityAction@19.10.2
      with:
        # GitHub access token with read/write privileges to GitHub Packages
        gp-token: abc
        # WS environment destination url
        ws-destination-url: http://test.com
        # WS organization api key
        ws-api-key: ${{ secrets.WS_KEY }}
        # WS user key
        ws-user-key: ${{ secrets.WS_KEY }}

